enableGlobalCache: true

enableHardenedMode: false

enableProgressBars: true

nodeLinker: node-modules

npmScopes:
  _default:
    npmAuthToken: "${CI_NPM_AUTH_TOKEN:-placeHolderToken}"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
