# environments:
#   default:
#     values:
#       - default-values.yaml
---

repositories:
  - name: joseph-chat
    url: https://sotojn.github.io/joseph-test-repo/charts

helmDefaults:
  wait: true

releases:

  - name: joseph-chat
    namespace: dev
    version: 1.0.2
    chart: joseph-chat/joseph-chat-chart
    values:
      - image:
          tag: "1.0.0"
        service:
          type: NodePort
          nodePort: 30565
