name: build-test
run-name: ${{ github.actor }} has triggered a build of the thing

on:
  push:
    branches:
      - '*'
      - '!main'

jobs: 
    build_and_release_docker:
        runs-on: ubuntu-latest

        permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write

        env:
          REGISTRY: ghcr.io
          IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/joseph-chat"

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Get full image tag
              id: full_tag
              run: |
                TAG=${{ github.event.release.tag_name }}
                echo "FULL_IMAGE_NAME=${{ env.IMAGE_NAME }}:${TAG#v}-test" >> $GITHUB_ENV

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                platforms: linux/arm64,linux/amd64

            - name: Print Release Tag
              run: | 
                echo "Releasing image ${{ env.FULL_IMAGE_NAME }} to ghcr"

            - name: Build
              uses: docker/build-push-action@v6
              with:
                context: .
                platforms: linux/arm64,linux/amd64
                build-args: |
                    "GITHUB_SHA=${{ github.sha }}"
                provenance: false
                sbom: false
                pull: true
                push: true
                file: ./Dockerfile
                tags: "${{ env.FULL_IMAGE_NAME }}"
                outputs: type=oci